# Generated by Django 3.2.9 on 2021-12-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookingDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountHolderName', models.CharField(max_length=100)),
                ('AccountNumber', models.CharField(max_length=100)),
                ('ExpiryDate', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=100, null=True)),
                ('BookedId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookedid', to='BookingDetails.booking')),
            ],
        ),
    ]
